In [1]:
# Import relevant packages
from utils import save_data
import os
import numpy as np
from computeShapeHistogram import computeShapeHistogram
from utils import load_data
from Mesh import Mesh
from logisticRegressionTrain import logisticRegressionTrain
from logisticRegressionTest import logisticRegressionTest

In [2]:
# Import train and test directories
# Dataset directory
train_dir = '../dataset/train'
test_dir = '../dataset/test'

In [3]:
# Run training module for Logistic Regression without regularisation
w, min_y, max_y = logisticRegressionTrain(train_dir,reg_lambda=0,loadData=True)

In [4]:
# Print weights and biases (note that the last component is for bias according to code)
w

array([-0.16717376,  0.24629455, -0.3909624 ,  0.63088938,  0.62272038,
       -1.03512446, -3.05214736, -2.32609861,  7.47462549, -3.56341105,
       -0.21467659])

In [5]:
# Run the testing module on test data with training weights
t, test_err,pred_lab,true_lab = logisticRegressionTest(test_dir, w, min_y, max_y, loadData=True)

Test classification error : 0.00%


In [6]:
# Print E
# t: Prediction probability
# test_err = 1-accuracy
# pred_lab: predicted label
#true_lab: true_label
t,test_err,pred_lab,true_lab

(array([0.85185345, 0.24020233, 0.25967558, 0.82864647, 0.29375736,
        0.1163407 , 0.24675039, 0.80369612, 0.86373132, 0.11746774,
        0.86073768, 0.72934597, 0.09844256, 0.84635711, 0.81620579,
        0.31688655, 0.83495123, 0.84140206, 0.25127242, 0.10207459,
        0.27509076, 0.52171499]),
 0.0,
 [1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1],
 array([[1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1]]))

In [7]:
# Calculate accuracy below
100-test_err*100

100.0